service: default
runtime: python37

basic_scaling:
    max_instances: 10
    idle_timeout: 5m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 app:server